### ISSUE TITLE
namespace custom unbound here

### ISSUE THREAD

**Issue by lifeisdream** [BelkaLab/Android-Toggle-Switch#36]
can't set attributes with custom: textToggleLeft 
version us.belka:androidtoggleswitch:1.2.2

**Comment by shangyilim** [comment]
Check your parent layout to see whether the namespace for `http://schemas.android.com/apk/res-auto`  is present. By default you should have one  like 
```
    xmlns:app="http://schemas.android.com/apk/res-auto"
```
if you do have it, then  change it to `app:textToggleLeft` instead of `custom:textToggleLeft` 

if you dont have it, you can add the namespace to your parent layout:
```
xmlns:custom="http://schemas.android.com/apk/res-auto"
```
