### ISSUE TITLE
I can't get the values of ToggleSwitch

### ISSUE THREAD

**Issue by AlecSPB** [BelkaLab/Android-Toggle-Switch#40]
My code is
```java
this.toggleSwitch.setOnChangeListener(new ToggleSwitch.OnChangeListener() {
    @Override
    public void onToggleSwitchChanged(int toggle_position) {
        MainActivity.this.arParam = toggle_position;
    }
});
```
Event does not fire
```java
public void onToggleSwitchChanged(int toggle_position) {
    MainActivity.this.arParamAngle = toggle_position;
}
```

**Comment by llollox** [comment]
I've tried your code and it works for me.
I'm in trouble figuring out what your problem is. 
Can you provide more code about your problem?

Anyway, @AlecSPB I have made a fork of this library that solves many issues.
The api are almost the same as the previous one.
Try with it, it should solve your issue ;)
Let me know about it.

Check it out at https://github.com/llollox/Android-Toggle-Switch
