### ISSUE TITLE
Multiple checks/selections ?

### ISSUE THREAD

**Issue by RahulSDeshpande** [BelkaLab/Android-Toggle-Switch#6]
Hi,

Your lib is really cool & UI is very convincing :)

Is it possible to have a multiple checks/selections using this lib & get the checked & unchecked items later programmatically ?

Cheers :+1:

**Comment by llollox** [comment]
Unfortunately, this functionality is not implemented right now.
I'm working on fixing the open issues of my library.
I'll see also for this soon! 

Thank you for your suggestion.

**Comment by RahulSDeshpande** [comment]
Sure @llollox :D

I am digging into the lib.
Lets see if I could help you.

Cheers :+1:

**Comment by llollox** [comment]
In this new version (1.2.0) I've implemented the support for multi checks.

I've implemented another widget in order to support this functionality.
You have to use the widget called "MultipleToggleSwitch" instead the normal "ToggleSwitch".

This is explained also into the documentation.

Please, let me know if this solves your problem!

**Comment by RahulSDeshpande** [comment]
Aaha !!

Perfecto :+1: 

Thanks a lot @llollox :D
